
all:
	$(MAKE) -C $(shell git rev-parse --show-toplevel) all

.PHONY: all clean debug run

clean:
	$(MAKE) -C $(shell git rev-parse --show-toplevel) clean

debug:
	$(MAKE) -C $(shell git rev-parse --show-toplevel) debug

run:
	$(MAKE) -C $(shell git rev-parse --show-toplevel) run

